"""added title to posts

Revision ID: 354b59484a1a
Revises: 7ea6bd3c55f3
Create Date: 2024-02-19 04:50:48.974351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354b59484a1a'
down_revision = '7ea6bd3c55f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
